@startuml DSS_Ajouter_Question
title DSS ajouter question
hide footbox
actor ":Enseignant" as professeur
participant ":Systeme" as systeme

professeur ->  systeme : recupererTousEspaceCours(token : String)
professeur <-- systeme : liste des espaceCours de l'enseignant
professeur -> systeme : recupererToutesQuestionsEspaceCours(idEspaceCours : int)
professeur <-- systeme : questions associées à l'espaceCours

loop !terminerQuestion
professeur -> systeme : ajouterQuestion(tags : String[], nom : String, \ntexteQuestion : String, reponse : boolean,\ntexteBonneReponse : String, texteMauvaiseReponse : String)
systeme --> professeur : liste de questions mise à jour
end
professeur -> systeme : terminerAjouterQuestion()


@enduml