@startuml ajouterQuestionOld
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour ajouter question
participant ":EnseignantControleur" as sga
participant "operationCours : OperationCours" as opCours
participant "operationQuestion : OperationQuestion" as opQuestion
participant "q:Question" as question

->sga : cours = recupererCoursSga(token)
note left : Selon Contôleur,\nreçoit la première opération système
sga->opCours: cours = recupererCours(token)
note left : Selon expert, l'information Sgb est l'expert,\ncar il contient toutes les informations\nutiles pour les cours
loop [!terminerQuestion]
->gestionnaireQuestion : ajouterQuestion(idEspaceCours,\ntags,nom,texteQuestion,\nreponse,texteBonneReponse,\ntexteMauvaiseReponse)
 note left : Selon contôlleur de session,\nreçoit la deuxième opération système 
gestionnaireQuestion->universite : ajouterQuestion(idEspaceCours,\ntags,nom,texteQuestion,\nreponse,texteBonneReponse,\ntexteMauvaiseReponse)
gestionnaireQuestion -> universite: c = recupererUnCours(id)
  note left : Selon expert, universite est l'expert,\ncar il contient toutes les informations\nutiles pour les EspaceCours
gestionnaireQuestion-> cours : ajouterQuestion(tags,nom,texteQuestion,\nreponse,texteBonneReponse,\ntexteMauvaiseReponse)
  note left : Selon expert, espaceCours est l'expert,\ncar il contient toutes les informations\nutiles pour les questions
create question
  cours->question : q = create()
    note left : selon Créateur\n(EspaceCours \n contient Question)
cours->cours : ajouterQuestion(q)
  note left : Selon expert, espaceCours est l'expert,\ncar il contient toutes les informations\nutiles pour les questions
end
-> sga : terminerAjouterQuestion()
note left : Ce n'est pas une opération système, \nmais nous aide à déterminer la fin de la boucle
  -> sga : information = recupererCoursSga(idGroupeCours)
  note left : EnseignantControlleur est l'objet racine.\nContrôleur ne s'applique pas ici,\ncar il ne s'agit pas d'une opération système
  sga -> opQuestion : information = recupereCours(token)
@enduml

@startuml recupererCoursSgaQuestion
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU recupererToutesQuestionsEspaceCours
participant ":GestionnaireQuestion" as gestionnaireQuestion
participant "universite : Universite" as universite
participant "espaceCours : EspaceCours" as cours
->gestionnaireQuestion : questions = recupererToutesQuestionsEspaceCours(idEspaceCours)
note left : Selon Contôleur,\nreçoit opération système
gestionnaireQuestion -> universite : espaceCours = recupererUnEspaceCours(idEspaceCours)
note left : Selon expert, universite a toutes les\ninformations pour recupererUnEspaceCours
gestionnaireQuestion -> cours : questions = recupererToutesQuestions()
note left : Selon expert, espaceCours a toutes les\ninformations pour recupererToutesQuestions
@enduml

@startuml ajouterQuestionFinal
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour ajouterQuestion
participant ": GestionnaireQuestion" as gestionnaireQuestion
participant "universite : Universite" as universite
participant "espaceCours : EspaceCours" as cours
participant "q:Question" as question

loop [!terminerQuestion]
  ->gestionnaireQuestion : questions = ajouterQuestion(idEspaceCours,\ntags,nom,texteQuestion,\nreponse,texteBonneReponse,\ntexteMauvaiseReponse)
  note left : Selon contôlleur,\nreçoit l'opération système 
  gestionnaireQuestion -> universite : espaceCours = recupererUnEspaceCours(idEspaceCours)
  note left : Selon expert, universite a toutes les\ninformations pour recupererUnEspaceCours
  gestionnaireQuestion -> cours : ajouterQuestion(tags,nom,texteQuestion,\nreponse,texteBonneReponse,\ntexteMauvaiseReponse)
  note left : Selon forte cohésion, espaceCours a la reponsabilité\nde gérer l'ajout des questions.
  cours-->question** : create(tags,nom,texteQuestion,\nreponse,texteBonneReponse,\ntexteMauvaiseReponse)
  note left : selon Créateur\n(EspaceCours \n contient Question)
  cours->cours : ajouterQuestion(q)
  note left : Selon expert, espaceCours est l'expert,\ncar il contient toutes les informations\nutiles pour les questions
  gestionnaireQuestion -> cours : questions = recupererToutesQuestions()
  note left : Selon expert, espaceCours est l'expert,\ncar il contient toutes les informations\nutiles pour les questions
end
-> gestionnaireQuestion : terminerAjouterQuestion()
note left : selon controleur, permet de sortir de la boucle
@enduml