@startuml ajouterQuestionOld
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour ajouter question
participant ":EnseignantControleur" as sga
participant "operationCours : OperationCours" as opCours
participant "operationQuestion : OperationQuestion" as opQuestion
participant "q:Question" as question

->sga : cours = recupererCoursSga(token)
note left : Selon Contôleur,\nreçoit la première opération système
sga->opCours: cours = recupererCours(token)
note left : Selon expert, operationCours est l'expert,\ncar il contient toutes les informations\nutiles pour les cours
loop [!terminerQuestion]
-> sga : ajouterQuestion(numeroGroupe,\ntags,nom,texteQuestion,\nreponse,texteBonneReponse,\ntexteMauvaiseReponse)
 note left : Selon Contôleur,\nreçoit la deuxième opération système 
  sga->opQuestion : ajouterElement(numeroGroupe,\ntags,nom,texteQuestion,\nreponse,texteBonneReponse,\ntexteMauvaiseReponse)
  note left : Selon fabrication pure : operationQuestion\nne represente pas un problème du domaine,\nmais permet de réduire le couplage et d'augmenter la cohésion
  create question
  opQuestion->question : q = create()
  note left : selon Créateur\n(EnseignantControlleur\nutilise groupeCours)
  opQuestion->opQuestion : ajouterQuestion(q)
  note left : Selon expert, operationQuestion est l'expert,\ncar il contient toutes les informations\nutiles pour les questions
end
-> sga : terminerAjouterQuestion()
note left : Ce n'est pas une opération système, \nmais nous aide à déterminer la fin de la boucle
  -> sga : information = recupererCoursSga(idGroupeCours)
  note left : EnseignantControlleur est l'objet racine.\nContrôleur ne s'applique pas ici,\ncar il ne s'agit pas d'une opération système
  sga -> opQuestion : information = recupereCours(token)
  note left :   note left : Selon expert, operationQuestion est l'expert,\ncar il contient toutes les informations\nutiles pour les questions
@enduml

@startuml recupererCoursSgaQuestion
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU recupererCoursSgaquestion
participant ":EnseignantControleur" as sga
participant "operationCours : OperationCours" as opCours
->sga : questions = recupererCoursSgaQuestion(token, idCours, numeroGroupeCours)
note left : Selon Contôleur,\nreçoit la première opération système
sga->opCours: questions = recupererCours(token, idCours, numeroGroupeCourss)
note left : Selon expert, l'information Sgb est l'expert,\ncar il contient toutes les informations\nutiles pour les cours
@enduml

@startuml ajouterQuestionFinal
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour ajouterQuestion
participant ":EnseignantControleur" as sga
participant "operationCours : OperationCours" as opCours
participant "operationQuestion : OperationQuestion" as opQuestion
participant "q:Question" as question
loop [!terminerQuestion]
-> sga : ajouterQuestion(numeroGroupe,\ntags,nom,texteQuestion,\nreponse,texteBonneReponse,\ntexteMauvaiseReponse)
 note left : Selon Contôleur,\nreçoit la deuxième opération système 
  sga->opQuestion : ajouterElement(numeroGroupe,\ntags,nom,texteQuestion,\nreponse,texteBonneReponse,\ntexteMauvaiseReponse)
  note left : Selon fabrication pure : operationQuestion\nne represente pas un problème du domaine,\nmais permet de réduire le couplage et d'augmenter la cohésion
  create question
  opQuestion->question : q = create()
  note left : selon Créateur\n(EnseignantControlleur\nutilise groupeCours)
  opQuestion->opQuestion : ajouterQuestion(q)
  note left : Selon expert, operationQuestion est l'expert,\ncar il contient toutes les informations\nutiles pour les questions
end
@enduml

@startuml terminerAjouterQuestion
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour ajouterQuestion
participant ":EnseignantControleur" as sga
participant "operationCours : OperationCours" as opCours
 -> sga : information = recupererCoursSga(idGroupeCours)
  note left : EnseignantControlleur est l'objet racine.\nContrôleur ne s'applique pas ici,\ncar il ne s'agit pas d'une opération système
  sga -> opCours : information = recupereCours(token)
  note left : Selon expert, operationQuestion est l'expert,\ncar il contient toutes les informations\nutiles pour les questions
@enduml