@startuml recupererToutQuestionnaires
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour recupererToutQuestionnaires
participant ": GestionnaireQuestionnaire" as gestionnaireQuestion
participant "universite : Universite" as universite
participant "espaceCours : EspaceCours" as cours
-> gestionnaireQuestion : questionnaires = recupererToutQuestionnaires(idEspaceCours)
note left : Selon controleur,\ncontrôleur de session
gestionnaireQuestion -> universite : espaceCours = recupererUnEspaceCours(idEspaceCours)
note left : Selon expert, universite a toutes les\ninformations pour recupererUnEspaceCours
gestionnaireQuestion -> cours : questionnaires = recupererToutQuestionnaires()
note left : Selon expert, espaceCours contient\ntous ces questionnaires
@enduml

@startuml ajouterQuestionnaireGenerale
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour ajouterQuestionnaire
participant ": GestionnaireQuestionnaire" as gestionnaireQuestion
participant "universite : Universite" as universite
participant "espaceCours : EspaceCours" as cours
participant "newQuestionnaire : Questionnaire" as questionnaire
participant "questionnaires : Questionnaire[]" as questionnaires
-> gestionnaireQuestion : tags = creerQuestionnaire(idEspaceCours)
note left : Selon controleur,\ncontrôleur de session
gestionnaireQuestion -> universite : espaceCours = recupererUnEspaceCours(idEspaceCours)
note left : Selon expert, universite a toutes les\ninformations pour recupererUnEspaceCours
gestionnaireQuestion -> cours : creerQuestionnaire(idEspaceCours, description, etat)
note left : Selon expert, espaceCours contient\ntous ces questionnaires
cours --> questionnaire** : newQuestionnaire = create(id, description, etat)
note left : Selon createur, EspaceCours\ncontient Questionnaire
cours -> questionnaires : push(newQuestionnaire)
note left : Selon expert
gestionnaireQuestion -> cours : tags = recupererTagQuestions()
note left : Selon expert
@enduml