@startuml creerNouveauCours
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour créer un nouveau Cours
participant ":EnseignantControleur" as sga
participant "<<Actor>> : Sgb" as sgb
participant "OperationCours : OperationCours" as map
participant "c:EspaceCours" as cours

->sga : cours = recupererCoursSgb(token)
note left : Selon Contôleur,\nreçoit la première opération système
sga->sgb: cours = recupererCours(token)
note left : Selon expert, l'information Sgb est l'expert,\ncar il contient toutes les informations\nutiles pour les cours
-> sga : ajouterCours(numeroGroupe)
 note left : Selon Contôleur,\nreçoit la deuxième opération système
  create cours
  sga->cours : c = create()
  note left : selon Créateur\n(EnseignantControlleur\nutilise groupeCours)
  sga->map : ajouterCours(tokenEnseignant, c)
  -> sga : information = recupererCoursSga(token)
  note left : EnseignantControlleur est l'objet racine.\nContrôleur ne s'applique pas ici,\ncar il ne s'agit pas d'une opération système
  sga -> map : information = recupereCours(token)
@enduml