@startuml recupererCoursSgb
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU. recupererCoursSgb
participant ":GestionnaireCours" as sga
participant "<<Actor>> : Sgb" as sgb

->sga : cours = recupererCoursSgb(token)
note left : Selon Contôleur,\nreçoit la première opération système
sga->sgb: cours = recupererCours(token)
@enduml