@startuml creerNouveauCours
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU. ajouter cours
participant ":GestionnaireCours" as controlleur
participant "Université" as sga
participant "c:Cours" as cours

-> controlleur : ajouterCours(numeroGroupe,tokenEnseignant)
  controlleur->sga : ajouterCours(tokenEnseignant, c)
  note right : Selon expert, Université a toute\nles informations requises\npour créer un cours
  create cours
  sga->cours : c = create()
  -> controlleur : information = recupererCours(token)
note right : Selon expert, Université a toute\nles informations requises\npour récupérer un cours
  controlleur -> sga : information = recupereCours(token)
  @enduml