@startuml creerNouveauCours
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU. ajouter cours
participant ":GestionnaireCours" as controlleur
participant "Université" as sga
participant "c:EspaceCours" as cours

-> controlleur : ajouterCours(numeroGroupe,tokenEnseignant)
  controlleur->sga : ajouterCours(numeroGroupe,tokenEnseignant)
  note right : Selon expert, Université a toute\nles informations requises\npour créer un cours
  create cours
  sga->cours : create()
  -> controlleur : information = recupererCours(tokenEnseignant)
note right : Selon expert, Université a toute\nles informations requises\npour récupérer un cours
  controlleur -> sga : information = recupereCours(tokenEnseignant)
  @enduml