@startuml DSS_Modifier_Question
title DSS modifier question
hide footbox
actor ":Enseignant" as prof
participant ":Systeme" as sys

prof -> sys : recupererUneQuestion(idEspaceCours : int, idQuestion : int)
sys --> prof : valeurs actuelles de la question à modifier
prof -> sys : modifierQuestion(idQuestion : int, tags : String[], nom : String, \ntexteQuestion : String, reponse : boolean,\ntexteBonneReponse : String, texteMauvaiseReponse : String)
sys --> prof : question modifiée
@enduml
