@startuml modifierQuestionFinal
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU modifierUneQuestion
participant ":GestionnaireQuestion" as gestionQ
participant "universite : Universite" as universite
participant "espaceCours : EspaceCours" as cours
-> gestionQ : modifierQuestion(idEspaceCours,\nIdQuestion, tags,\nnom, texteQuestion,\nreponse, texteBonneReponse,\ntexteMauvaiseReponse)
note left : Selon controlleur, reçoit\nl'opération système
gestionQ -> universite : espaceCours = recupererUnEspaceCours(idEspaceCours)
note left : Selon expert, universite a toutes les\ninformations pour recupererUnEspaceCours
gestionQ -> cours : modifierQuestion(IdQuestion,\ntags, nom, texteQuestion,\nreponse, texteBonneReponse,\ntexteMauvaiseReponse)
note left : Selon expert, espaceCours a toutes les\ninformations pour recupererToutesQuestions
@enduml