@startuml DSS_Supprimer_Question
title DSS supprimer question
hide footbox
actor ":Enseignant" as professeur
participant ":Systeme" as systeme

professeur ->  systeme : recupererUneQuestion(token : String, idQuestion : int)
professeur <-- systeme : valeurs actuelles de la question à supprimer
professeur -> systeme : supprimerQuestion(idEspaceCours, IdQuestion)
professeur <-- systeme : questions associées au cours

@enduml