@startuml recupererTouteQuestion
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour récupérer toutes les questions créées d'un enseignant
participant "operationCours : OperationCours" as opCours
participant "universite : Universite" as universite
participant "espacesCours[i] : EspaceCours" as cours

->opCours : questions = recupererToutesQuestions(token)
note left : Selon Contôleur,\nreçoit la première opération système
opCours -> universite : espacesCours = recupererTousEspaceCours(token)
note left : Selon expert, universite a toutes les\ninformations pour recupererTousEspaceCours
loop espacesCours.length
opCours -> cours : questions += recupererToutesQuestions()
note left : Selon expert, chaque espaceCours a toutes les\ninformations pour\nrecupererToutesQuestions de l'espaceCours en cours
end
@enduml

@startuml recupererUneQuestion
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour récupérer une question créée d'un enseignant
participant "operationCours : OperationCours" as opCours
participant "universite : Universite" as universite
participant "espaceCours : EspaceCours" as cours

->opCours : questions = recupererUneQuestion(idEspaceCours, idQuestion)
note left : Selon Contôleur,\nreçoit l'opération système
opCours -> universite : espaceCours = recupererUnEspaceCours(idEspaceCours)
note left : Selon expert, universite a toutes les\ninformations pour recupererUnEspaceCours
opCours -> cours : questions = recupererUneQuestion(IdQuestion)
note left : Selon expert, espaceCours a toutes les\ninformations pour recupererUneQuestion
@enduml