@startuml recupererUnDevoir
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour recupererUnDevoir
participant ":GestionnaireDevoir" as gestionnaireDevoir
participant ":Universite" as universite
participant "espaceCours : EspaceCours" as cours
participant "devoirs : Devoirs[]" as devoirs

-> gestionnaireDevoir : devoir = recupererUnDevoir(idEspaceCours: number,\nIdDevoir: number)
note left : Selon contrôleur,\ncontôleur de session
gestionnaireDevoir -> universite : espaceCours = recupererUnEspaceCours(idEspaceCours : int)
note left : Selon expert, universite\ncontient les espaceCours
gestionnaireDevoir -> cours : devoir = recupererUnDevoir(IdDevoir)
note left : Selon expert, espaceCours\ncontient les devoirs
cours -> devoirs : devoir = find(idDevoir)
note left : Selon expert, devoirs est l'attribut\nd'espaceCours qui stocke les devoirs
@enduml

