@startuml MDD
skinparam defaultfontname Verdana
skinparam RoundCorner 20
skinparam linetype ortho

title Modèle du domaine (adapté au Cas d'utilisation \n ajouter et récupérer )

class Cours {
    id : int
    nom : String
}


class Enseignant {
    token : String
}

class Etudiant {
    nom : String
}

class Tag{
    nom : String
}
class Devoir{
    id: int
    nom: String
}

class Remise{
    id: int
    idEtudiant:int
}

enum Etat{
    NonRemis
    Remis
    RemisCorrige
}

class Question{
    id : int
    nom : String
    texteQuestion : String
    reponse : boolean
    texteBonneReponse : String
    texteMauvaiseReponse : String
}

class Questionnaire{
    id: int
    description: String
}

class EspaceCours{
}
Devoir "1"--"*" Remise : contient >
Remise"1"--"1" Etat : possède >
EspaceCours "1"--"1..*" Devoir: contient >
Enseignant "1"--"1..*" EspaceCours : enseigne >
Université "1"--"*" Enseignant : emploie >
Cours "1"-- "1" EspaceCours : décrit >
Université "1"--"*" Cours : contient >
EspaceCours "1"-- "*"Etudiant : est_suivi_par >
Question "1" -- "*"Tag : < catégorise
Questionnaire "1"--"1..*" Question : contient >
Questionnaire"1"--"1" Remise : possède >
Université "1"--"*" EspaceCours : contient >
Université "1"--"*" Etudiant : est-inscrit-à <
Question "*"--"1" EspaceCours : contient <
Questionnaire "*"--"1" EspaceCours : contient >
@enduml