@startuml MDD
skinparam defaultfontname Verdana
skinparam RoundCorner 20
skinparam linetype ortho

title Modèle du domaine (adapté au Cas d'utilisation \n ajouter et récupérer )

class Cours {
    id : int
    nom : String
}


class Enseignant {
    token : String
}

class Etudiant {
    nom : String
}

class Tag{
    nom : String
}

class Question{
    id : int
    nom : String
    texteQuestion : String
    reponse : boolean
    texteBonneReponse : String
    texteMauvaiseReponse : String
}

class EspaceCours{
}

Enseignant "1"--"1..*" EspaceCours : enseigne >
Université "1"--"*" Enseignant : emploie >
Cours "1"-- "1" EspaceCours : décrit >
Université "1"-up-"*" Cours : contient >
EspaceCours "1"-- "*"Etudiant : est_suivi_par >
Question "1" -- "*"Tag : < catégorise
Université "1"--"*" EspaceCours : contient >
Université "1"-right-"*" Etudiant : est-inscrit-à <
Question "*"-up-"1" EspaceCours : contient <
@enduml