@startuml DSS_Récupérer_Cours
title DSS récupérer cours
hide footbox
actor ":Enseignant" as professeur
participant ":Systeme" as systeme

professeur ->  systeme : recupererTousCoursSga(token : String)
professeur <-- systeme : liste de cours de l'enseignant
professeur -> systeme : recupererUnCoursSga(token : String, idCours : String)
professeur <-- systeme : information du cours et affiche la liste des étudiants inscrits.
@enduml