@startuml DSS_Récupérer_Cours
title DSS récupérer espaceCours
hide footbox
actor ":Enseignant" as professeur
participant ":Systeme" as systeme

professeur ->  systeme : recupererTousEspaceCours(token : String)
professeur <-- systeme : liste des espaceCours de l'enseignant
professeur -> systeme : recupererUnEspaceCours(idEspaceCours : String)
professeur <-- systeme : information du cours et affiche la liste des étudiants inscrits.
@enduml