@startuml récupérer tous les cours créés
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour récupérer tous les cours créés d'un enseignant
participant ":EnseignantControleur" as controleur
participant "coursService : CoursService" as mapCours

->controleur : cours = recupererTousCoursSga(token)
note right : selon Contrôleur\n(coursControleur est\nl'objet racine des cours\n recoit la première opération système)
controleur -> mapCours : cours = recupererTousCours(token)
note left : selon expert, CoursService a toute\nles informations requises\npour exécuter recupererTousCours
@enduml

@startuml récupérer un cours
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour récupérer un cours créé d'un enseignant
participant ":GestionnaireCours" as controleur
participant ":Université" as modele
->controleur : cours = recupererUnCours(token, idCours)
controleur -> modele : cours = recupererUnCours(token, idCours)
note left : selon expert, Université a toute\nles informations requises\npour exécuter recupererUnCours
@enduml