@startuml DSS_Retirer_Cours
title DSS retirer cours
hide footbox
actor ":Enseignant" as prof
participant ":Systeme" as sys

prof->  sys : recupererTousCours(token : String)
sys --> prof : liste des groupes-cours qu’enseigne l’enseignant
prof -> sys : recupererUnCours(token : String, idCours : String)
sys --> prof : information du cours et liste des etudiants\ninscrits dans le groupe-cours correspondant
prof -> sys : retirerCours(token : String, sigleCours : String, idGroupeCours : int)
sys --> prof : demande de confirmation
prof -> sys : confirmerSuppression(sigleCours : String, idGroupeCours : int)
sys --> prof : nouvelle liste de cours

@enduml
