@startuml supprimerUneQuestionSga
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour supprimerUneQuestionSga
participant ":GestionnaireCours" as controleur
->controleur : confirmation = supprimerUnCours(sigleCours : String, idGroupeCours : int)
note left : Selon Contôleur,\nreçoit la première opération système
@enduml

@startuml confirmerSuppression
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour confirmerSuppression
participant ":GestionnaireCours" as controleur
participant ":Université" as universite
-> controleur : confirmerSuppression(sigleCours : String, idGroupeCours : int)
note left : Selon Contôleur,\nreçoit la deuxième opération système
controleur -> universite : setSuppression(true)
note left : Changement valeur attribut comme quoi la\nsuppression a été confirmer par l'utilisateur
controleur -> universite : supprimerUneQuestion(question)
note left : Selon expert, Université a toute\nles informations requises\npour exécuter supprimerUnCours
@enduml 