@startuml supprimerEspaceCours
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour supprimerEspaceCours
participant ":GestionnaireCours" as controleur
participant ":Université" as universite
-> controleur : supprimerEspaceCours(idEspaceCours)
note left : Selon Contôleur,\nreçoit l'opération système
controleur -> universite : supprimerEspaceCours(question)
note left : Selon expert, Université a toutes\nles informations requises\npour exécuter supprimerUnCours
@enduml 