@startuml recupererUnQuestionnaire
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour recupererUnQuestionnaire
participant ": GestionnaireQuestionnaire" as gestionnaireQuestion
participant "universite : Universite" as universite
participant "espaceCours : EspaceCours" as cours
participant "questionnaires : Questionnaire[]" as questionnaires

-> gestionnaireQuestion : questionnaire = recupererUnQuestionnaire(idEspaceCours, idQuestionnaire)
note left : Selon controleur,\ncontrôleur de session
gestionnaireQuestion -> universite : espaceCours = recupererUnEspaceCours(idEspaceCours)
note left : Selon expert, universite a toutes les\ninformations pour recupererUnEspaceCours
gestionnaireQuestion -> cours : questionnaire = recupererUnQuestionnaire(idQuestionnaire)
note left : Selon expert
cours -> questionnaires : questionnaire = find(idQuestionnaire)
note left : Selon expert, questionnaires est\nl'attribut de EspaceCours\noù sont stockées les\nquestionnaires
@enduml