@startuml DSS_Ajouter_Devoir
title DSS Ajouter Devoir
hide footbox
actor ":Enseignant" as professeur
participant ":Systeme" as systeme

professeur ->  systeme : recupererTousEspaceCours(token : number)
professeur <-- systeme : liste des espaceCours de l'enseignant\net le nombre de devoirs associés à chacun
professeur -> systeme : recupererTousDevoirsEspaceCours(idEspaceCours : int)
professeur <-- systeme : listes de devoirs associées à l'espaceCours
loop !terminerAjouterDevoir
professeur -> systeme : ajouterDevoir(nom: string, \ndescription: string, \nnoteMaximale: number, \ndateDebut: String, \ndateFin: String, \nvisible: boolean)
systeme --> professeur : liste de devoirs mise à jour
end
professeur -> systeme : terminerAjouterDevoir()
@enduml