@startuml recupererTousDevoirsEspaceCours
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour recupererTousDevoirsEspaceCours
participant ":GestionnaireDevoir" as gestionnaireDevoir
participant ":Universite" as universite
participant "espaceCours : EspaceCours" as cours

-> gestionnaireDevoir : devoirs = recupererTousDevoirsEspaceCours(idEspaceCours : int)
note left : Selon Contôleur,\nreçoit l'opération système
gestionnaireDevoir -> universite : espaceCours = recupererUnEspaceCours(idEspaceCours : int)
note left : Selon expert, universite\ncontient les espaceCours
gestionnaireDevoir -> cours : devoirs = recupererTousDevoirs()
note left : Selon expert, espaceCours\ncontient les devoirs
@enduml

@startuml ajouterDevoir
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour ajouter devoir
participant ":GestionnaireDevoir" as gestionnaireDevoir
participant ":Universite" as universite
participant "espaceCours : EspaceCours" as cours
participant "d : Devoir" as devoir
participant "devoirs : Devoirs[]" as devoirs

loop [!terminerDevoir]
  ->gestionnaireDevoir : devoir = ajouterDevoir(idEspaceCours, id, \nnom, description, noteMaximale,\ndateDebut, dateFin, visible)
  note left : Selon contôlleur,\nreçoit l'opération système 
  gestionnaireDevoir -> universite : espaceCours = recupererUnEspaceCours(idEspaceCours)
  note left : Selon expert, universite a toutes les\ninformations pour recupererUnEspaceCours
  gestionnaireDevoir -> cours : ajouterDevoir(id, nom, description, noteMaximale, \ndateDebut, dateFin,visible)
  note left : Selon forte cohésion, espaceCours a la reponsabilité\nde gérer l'ajout des devoirs.
  cours-->devoir** : create(id, nom, description, noteMaximale, \ndateDebut, dateFin,visible)
  note left : Selon créateur, espaceCours\ncontient les devoirs qui\nlui sont associés
  cours->devoirs : push(d)
  note left : Selon expert, devoirs est l'attribut\nd'espaceCours qui stocke les devoirs
  gestionnaireDevoir -> cours : devoir = recupererTousDevoirs()
  note left : Selon expert
end
-> gestionnaireDevoir : terminerAjouterDevoir()
note left : Permet sortir de la boucle

@enduml