@startuml creerNouveauCours
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour créer un nouveau Cours
participant ":SGA" as sga
->sga : creerNouveauCours(token)
participant "c:Cours" as cours
participant "<<Actor>> : \n SGB" as sgb
participant "cours : \n Map<String,Cours>" as map
sga-->sgb: response = getCourses(token)
loop response.hasNext()
  create cours
  sga-->cours : c = create()
  note left : selon Créateur\n(SGA\n//agrège// Cours)
  sga->map : put(c)
  note right : selon Expert
end loop
<--sga : cours
@enduml