@startuml creerNouveauCours
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour créer un nouveau Cours
participant ":EnseignantControlleur" as sga
participant "<<Actor>> : \n SGB" as sgb
participant "coursService : CoursService" as map
participant "c:groupeCours" as cours

->sga : cours = recupererCoursSGB(token)
sga->sgb: response = recupererCours(token)
-> sga : ajouterCours(numeroGroupe)
  create cours
  sga->cours : c = create()
  note left : selon Créateur\n(SGA\n//agrège// Cours)
  sga->map : ajouterCours(token, c)
  note right : selon Expert
  -> sga : information = recupererCoursSGA(token)
  note left : opération pour l'affichage,\npas une opération système
  sga -> map : information = recupereCours(token)
@enduml