@startuml 
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour récupérer un cours d'un enseignant
participant ":CoursControleur" as coursControleur
->coursControleur : recupererCours(idEnseignant, idCours)
note right : selon Contrôleur\n(CoursControleur est\nl'objet racine des cours)
coursControleur -> coursControleur : cours = recupererCours(idEnseignant)
note right : Obtenir tous les cours de l'enseignant
participant "cours:\nMap<String, Cours>" as CollectionCours
coursControleur -> CollectionCours : c = chercher(idCours) 
note right : selon Transformer ID en objets
'TODO ecq je dois mettre un retour?
@enduml